@startuml
mplayer: UserStrSensor
mplayer_pid -> mplayer
mplayer -> mplayer
out_actual -> mplayer
mplayer -> mplayer_pid
mplayer -> playback_active
moc_toggle_pause: UserEventSensor
moc_toggle_pause -> moc_toggle_pause
mplayer_alive: PollingSensor
mplayer_alive -> mplayer_alive
mplayer_alive -> youtube
mplayer_alive -> mplayer
mplayer_alive -> livestreamer
start: UserEventSensor
mplayer_pid -> start
start -> start
out_actual -> start
start -> mplayer_pid
start -> playback_active
manual_mode: UserBoolSensor
manual_mode: Status: True
manual_mode -> manual_mode
manual_mode -> out_buffer
prev: UserEventSensor
prev -> prev
playback_active: PollingSensor
playback_active -> playback_active
playback_active -> out_buffer
next: UserEventSensor
next -> next
mplayer_pid: UserIntSensor
volumesensor: PollingSensor
volumesensor -> volumesensor
volumesensor -> volume
volume: UserIntSensor
volume: Status: 60
volume -> volume
after_reset: Program
after_reset: Status: True
out_buffer -> after_reset
dp_out_actual: DefaultProgram
dp_out_actual: Status: True
dp_out_actual -> out_actual
out_actual: RpioActuator
out_actual: Status: True
out_actual: <u>Active programs</u>
out_actual: out_buffer :: True
out_actual: dp_out_actual :: False
fsc: FileChangeSensor
stop: UserEventSensor
mplayer_pid -> stop
out_actual -> stop
stop -> stop
stop -> youtube
stop -> mplayer_pid
stop -> mplayer
stop -> livestreamer
stop -> playback_active
youtube: UserStrSensor
youtube -> youtube
mplayer_pid -> youtube
out_actual -> youtube
youtube -> mplayer_pid
youtube -> playback_active
radiodei: UserEventSensor
radiodei -> radiodei
radiodei -> mplayer
livestreamer: UserStrSensor
livestreamer -> livestreamer
mplayer_pid -> livestreamer
out_actual -> livestreamer
livestreamer -> mplayer_pid
livestreamer -> playback_active
out_buffer: BoolActuator
out_buffer: Status: True
out_buffer: <u>Active programs</u>
out_buffer: manual_mode :: 1
out_buffer: dp_out_buffer :: False
out_buffer -> out_buffer
out_buffer -> out_actual
moc_alive: PollingSensor
moc_alive -> moc_alive
moc_alive -> moc_play
restart_mpd: UserEventSensor
restart_mpd -> restart_mpd
dp_out_buffer: DefaultProgram
dp_out_buffer: Status: True
dp_out_buffer -> out_buffer
moc_play: UserStrSensor
moc_play -> moc_play
raspi1_alive: PollingSensor
raspi1_alive -> raspi1_alive
reset: UserBoolSensor
reset -> reset
reset -> reset
reset -> out_actual
reset -> start
current: PollingSensor
pause_mplayer: UserBoolSensor
mplayer_pid -> pause_mplayer
pause_mplayer -> pause_mplayer
@enduml