@startuml
skinparam state {
BackGroundColor<<actuator>> #FFCCFF
BackGroundColor<<program>> #FFFFCC
BackGroundColor<<sensor>> #CCFFCC
}
state "prog" as prog <<program>>
prog: Program
prog: Status: True
prog: Priority: 1
periodical -[#009933]-> prog
active_switch -[#009933]-> prog
prog -[#FF0000]-> target_actuator
state "target_actuator" as target_actuator <<actuator>>
target_actuator: IntActuator
target_actuator: prog :: 7.0
target_actuator: dp_target_actuator :: 0
state "periodical" as periodical <<sensor>>
periodical: IntervalTimerSensor
periodical: Status: 1.0
state "active_switch" as active_switch <<sensor>>
active_switch: UserBoolSensor
active_switch: Status: True
@enduml