@startuml
skinparam state {
BackGroundColor<<actuator>> #FFCCFF
BackGroundColor<<program>> #FFFFCC
BackGroundColor<<sensor>> #CCFFCC
}
state "high_prio_prg" as high_prio_prg <<sensor>>
high_prio_prg: UserBoolSensor
high_prio_prg: Status: True
high_prio_prg: Priority: 5.0
high_prio_prg -[#009933]-> high_prio_prg
high_prio_prg -[#FF0000]-> actuator
state "inactive_high_prio_prg" as inactive_high_prio_prg <<sensor>>
inactive_high_prio_prg: UserBoolSensor
inactive_high_prio_prg: Status: False
inactive_high_prio_prg: Priority: 6.0
inactive_high_prio_prg -[#009933]-> inactive_high_prio_prg
inactive_high_prio_prg -[#4C4C4C]-> actuator
state "low_prio_prg" as low_prio_prg <<sensor>>
low_prio_prg: UserBoolSensor
low_prio_prg: Status: True
low_prio_prg: Priority: -5.0
low_prio_prg -[#009933]-> low_prio_prg
low_prio_prg -[#0000FF]-> actuator
state "med_prio_prg" as med_prio_prg <<sensor>>
med_prio_prg: UserBoolSensor
med_prio_prg: Status: True
med_prio_prg: Priority: 1.0
med_prio_prg -[#009933]-> med_prio_prg
med_prio_prg -[#0000FF]-> actuator
state "actuator" as actuator <<actuator>>
actuator: FloatActuator
actuator: high_prio_prg :: 3.0
actuator: med_prio_prg :: 2.0
actuator: dp_actuator :: 0.0
actuator: low_prio_prg :: 1.0
@enduml